/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DATO.EmpresaRepetidoException;
import DATO.PuertasDAO;
import MODELO.Empresa;
import SERVICIO.EmpresaConNombreExistenteException;
import SERVICIO.EmpresaSERVICIO;
import SERVICIO.EmpresaSinPuertasException;
import SERVICIO.EmpresaVacioException;
import SERVICIO.CodigosSERVICIO;
import SERVICIO.NombreEmpresaInvalidoException;
import SERVICIO.PuertasSERVICIO;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author gube
 */
public class DatosCampusGUI extends javax.swing.JFrame {

    EmpresaSERVICIO cs = EmpresaSERVICIO.getInstancia();

    public DatosCampusGUI() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/IMG/parking.png")).getImage());
        if (!cs.isModificar()) {
            this.codigolbl.setText(CodigosSERVICIO.getInstancia().generarCodigo("CA"));
            this.txtNombreEmpresa.setText(null);
            this.btnAgregarPuerta.setEnabled(false);
        } else {
            this.codigolbl.setText(cs.getEmpresa().getCodigo());
            this.txtNombreEmpresa.setText(cs.getEmpresa().getNombre());
            this.notalbl.setText("");
        }

        if (PuertasSERVICIO.getInstancia().getListapuertas().isEmpty()) {
            this.btnAgregarParqueadero.setEnabled(true);
        }
        this.cantpuertaslbl.setText(Integer.toString(PuertasSERVICIO.getInstancia().getListapuertas().size()));
        if (cs.getEmpresa() == null) {
            this.cantparqlbl.setText(Integer.toString(0));
        } else {
            this.cantparqlbl.setText(Integer.toString(cs.getEmpresa().getParqueaderos().size()));
        }

    }

    public void nombreExistente(int a) {
        this.txtNombreEmpresa.setText(EmpresaSERVICIO.getInstancia().getEmpresa().getNombre());
        if (a == 0) {
            this.btnAgregarPuerta.setEnabled(true);
        } else if (a == 1) {
            this.btnAgregarPuerta.setEnabled(true);
            this.btnAgregarParqueadero.setEnabled(true);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        codigolbl = new javax.swing.JLabel();
        cantparqlbl = new javax.swing.JLabel();
        btnAgregarParqueadero = new javax.swing.JButton();
        btnAgregarPuerta = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        notalbl = new javax.swing.JLabel();
        btnAceptarEmpresa = new javax.swing.JButton();
        btnCancelarEmpresa = new javax.swing.JButton();
        cantpuertaslbl = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNombreEmpresa = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcionEmpresa = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        txtPropietarioEmpresa = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(813, 335));
        setSize(new java.awt.Dimension(813, 335));
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.setOpaque(false);

        codigolbl.setForeground(new java.awt.Color(255, 255, 255));
        codigolbl.setText("Cam001");

        cantparqlbl.setBackground(new java.awt.Color(204, 204, 204));
        cantparqlbl.setForeground(new java.awt.Color(255, 255, 255));
        cantparqlbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cantparqlbl.setText("0");

        btnAgregarParqueadero.setText("Parqueaderos");
        btnAgregarParqueadero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarParqueaderoActionPerformed(evt);
            }
        });

        btnAgregarPuerta.setText("Puertas");
        btnAgregarPuerta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarPuertaActionPerformed(evt);
            }
        });

        notalbl.setForeground(new java.awt.Color(255, 0, 0));
        notalbl.setText("Para crear una Empresa debe tener al menos 1 Parqueadero");

        btnAceptarEmpresa.setText("Aceptar");
        btnAceptarEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarEmpresaActionPerformed(evt);
            }
        });

        btnCancelarEmpresa.setText("Cancelar");
        btnCancelarEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarEmpresaActionPerformed(evt);
            }
        });

        cantpuertaslbl.setBackground(new java.awt.Color(204, 204, 204));
        cantpuertaslbl.setForeground(new java.awt.Color(255, 255, 255));
        cantpuertaslbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cantpuertaslbl.setText("0");

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Codigo:");
        jLabel3.setPreferredSize(new java.awt.Dimension(65, 16));

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Nombre:");
        jLabel2.setPreferredSize(new java.awt.Dimension(65, 16));

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Datos Empresa");

        jLabel5.setBackground(new java.awt.Color(204, 204, 204));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Descripción:");

        txtNombreEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreEmpresaActionPerformed(evt);
            }
        });
        txtNombreEmpresa.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtNombreEmpresaPropertyChange(evt);
            }
        });
        txtNombreEmpresa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreEmpresaKeyReleased(evt);
            }
        });

        txtDescripcionEmpresa.setColumns(20);
        txtDescripcionEmpresa.setRows(5);
        jScrollPane1.setViewportView(txtDescripcionEmpresa);

        jLabel6.setBackground(new java.awt.Color(204, 204, 204));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Propietario:");
        jLabel6.setPreferredSize(new java.awt.Dimension(65, 16));

        txtPropietarioEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPropietarioEmpresaActionPerformed(evt);
            }
        });
        txtPropietarioEmpresa.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtPropietarioEmpresaPropertyChange(evt);
            }
        });
        txtPropietarioEmpresa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPropietarioEmpresaKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPropietarioEmpresa))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
                                    .addComponent(txtNombreEmpresa))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnAceptarEmpresa)
                                .addGap(6, 6, 6)
                                .addComponent(btnCancelarEmpresa))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(btnAgregarParqueadero)
                                    .addGap(34, 34, 34)
                                    .addComponent(cantparqlbl, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(btnAgregarPuerta, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(34, 34, 34)
                                    .addComponent(cantpuertaslbl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(32, 32, 32))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(notalbl)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(codigolbl, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(318, 318, 318)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(13, 13, 13)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(15, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigolbl)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAgregarPuerta)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(cantpuertaslbl)))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAgregarParqueadero)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(cantparqlbl))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombreEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAceptarEmpresa)
                            .addComponent(btnCancelarEmpresa)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPropietarioEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(notalbl)
                .addGap(25, 25, 25))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(171, 171, 171)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(84, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 20, 760, 260);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/fondo3.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(-4, -5, 810, 320);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarEmpresaActionPerformed
        // TODO add your handling code here:
        cs.setModificar(false);
        this.setVisible(false);
        DatosEmpresasGUI lcg = new DatosEmpresasGUI();
        lcg.setVisible(true);
    }//GEN-LAST:event_btnCancelarEmpresaActionPerformed

    private void btnAgregarPuertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPuertaActionPerformed
        try {
            // TODO add your handling code here:
            String codigo = this.codigolbl.getText();
            String nombre = this.txtNombreEmpresa.getText();
            if (!cs.isModificar()) {

                int cantpuertas = PuertasSERVICIO.getInstancia().getListapuertas().size();
//                cs.crearEmpresa(codigo, nombre, cantpuertas);
            } else {
                cs.modificarEmpresa(codigo, nombre);
            }
            ListaPuertasGUI listaPuertasGUI = new ListaPuertasGUI();
            this.setVisible(false);
            listaPuertasGUI.setVisible(true);
        } catch (NombreEmpresaInvalidoException ex) {
            JOptionPane.showMessageDialog(this, "Ingrese un nombre de Campus");
        } 
//        catch (EmpresaConNombreExistenteException ex) {
//            JOptionPane.showMessageDialog(this, "Ya existe un campus con nombre: " + this.txtNombreEmpresa.getText());
//        }


    }//GEN-LAST:event_btnAgregarPuertaActionPerformed

    private void btnAgregarParqueaderoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarParqueaderoActionPerformed
        // TODO add your handling code here:
        if (this.txtNombreEmpresa.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Ingrese un nombre de Campus");
        } else {
            ListaParqueaderosGUI gUI = new ListaParqueaderosGUI();
            this.setVisible(false);
            gUI.setVisible(true);
        }
    }//GEN-LAST:event_btnAgregarParqueaderoActionPerformed

    private void btnAceptarEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarEmpresaActionPerformed
        try {
            if (!cs.isModificar()) {
                Empresa  empresa= new Empresa( codigolbl.getText(), txtNombreEmpresa.getText(), txtDescripcionEmpresa.getText(), txtPropietarioEmpresa.getText(),  null);
                
                cs.crearEmpresa(empresa);
//                cs.GuardarEmpresa(empresa);
                
                this.setVisible(false);
                DatosEmpresasGUI lcg = new DatosEmpresasGUI();
                lcg.setVisible(true);
                JOptionPane.showMessageDialog(this, "Campus Agregado Correctamente");
            } else {
                cs.GuardarEmpresaModificado(this.txtNombreEmpresa.getText());
                cs.setModificar(false);
                this.setVisible(false);
                DatosEmpresasGUI lcg = new DatosEmpresasGUI();
                lcg.setVisible(true);
                JOptionPane.showMessageDialog(this, "Campus Modificado Correctamente");
                PuertasDAO.getInstancia().mostrar();
            }
//        } catch (EmpresaRepetidoException ex) {
//            JOptionPane.showMessageDialog(this, "El campus ya existe");
        } catch (EmpresaConNombreExistenteException ex) {
            JOptionPane.showMessageDialog(this, "Ya existe un campus con nombre: " + this.txtNombreEmpresa.getText());
        } catch (EmpresaVacioException ex) {
            JOptionPane.showMessageDialog(this, "No puede Crear un Campus sin parqueaderos");
        } catch (NombreEmpresaInvalidoException ex) {
            JOptionPane.showMessageDialog(this, "Ingrese un nombre de Campus");
        } catch (EmpresaSinPuertasException ex) {
            JOptionPane.showMessageDialog(this, "No Puede Crear un Campus Sin Puertas");
        } catch (EmpresaRepetidoException ex) {
            Logger.getLogger(DatosCampusGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAceptarEmpresaActionPerformed

    private void txtNombreEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreEmpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreEmpresaActionPerformed

    private void txtNombreEmpresaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtNombreEmpresaPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreEmpresaPropertyChange

    private void txtNombreEmpresaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreEmpresaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreEmpresaKeyReleased

    private void txtPropietarioEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPropietarioEmpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPropietarioEmpresaActionPerformed

    private void txtPropietarioEmpresaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtPropietarioEmpresaPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPropietarioEmpresaPropertyChange

    private void txtPropietarioEmpresaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPropietarioEmpresaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPropietarioEmpresaKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DatosCampusGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DatosCampusGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DatosCampusGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DatosCampusGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DatosCampusGUI().setVisible(true);
            }
        });
    }

    public void agregarnombreExistente() {

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptarEmpresa;
    private javax.swing.JButton btnAgregarParqueadero;
    private javax.swing.JButton btnAgregarPuerta;
    private javax.swing.JButton btnCancelarEmpresa;
    private javax.swing.JLabel cantparqlbl;
    private javax.swing.JLabel cantpuertaslbl;
    private javax.swing.JLabel codigolbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel notalbl;
    private javax.swing.JTextArea txtDescripcionEmpresa;
    private javax.swing.JTextField txtNombreEmpresa;
    private javax.swing.JTextField txtPropietarioEmpresa;
    // End of variables declaration//GEN-END:variables

}
