/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.CampusRepetidoException;
import DAO.PuertasDAO;
import SERVICIO.CampusConNombreExistenteException;
import SERVICIO.CampusSERVICIO;
import SERVICIO.CampusSinPuertasException;
import SERVICIO.Campusvacioexception;
import SERVICIO.CodigosSERVICIO;
import SERVICIO.NombreCampusInvalidoException;
import SERVICIO.PuertasSERVICIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author gube
 */
public class DatosCampusGUI extends javax.swing.JFrame {

    CampusSERVICIO cs = CampusSERVICIO.getInstancia();

    public DatosCampusGUI() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/IMG/parking.png")).getImage());
        if (!cs.isModificar()) {
            this.codigolbl.setText(CodigosSERVICIO.getInstancia().generarCodigo("CA"));
            this.nombreCampusTXT.setText(null);
            this.puertabtn.setEnabled(false);
        } else {
            this.codigolbl.setText(cs.getCampus().getCodigo());
            this.nombreCampusTXT.setText(cs.getCampus().getNombre());
            this.notalbl.setText("");
        }

        if (PuertasSERVICIO.getInstancia().getListapuertas().isEmpty()) {
            this.parqbtn.setEnabled(false);
        }
        this.cantpuertaslbl.setText(Integer.toString(PuertasSERVICIO.getInstancia().getListapuertas().size()));
        if (cs.getCampus() == null) {
            this.cantparqlbl.setText(Integer.toString(0));
        } else {
            this.cantparqlbl.setText(Integer.toString(cs.getCampus().getParqueaderos().size()));
        }

    }

    public void nombreExistente(int a) {
        this.nombreCampusTXT.setText(CampusSERVICIO.getInstancia().getCampus().getNombre());
        if (a == 0) {
            this.puertabtn.setEnabled(true);
        } else if (a == 1) {
            this.puertabtn.setEnabled(true);
            this.parqbtn.setEnabled(true);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        codigolbl = new javax.swing.JLabel();
        cantparqlbl = new javax.swing.JLabel();
        parqbtn = new javax.swing.JButton();
        puertabtn = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        notalbl = new javax.swing.JLabel();
        nombreCampusTXT = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        cantpuertaslbl = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jButton3.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(520, 330));
        setSize(new java.awt.Dimension(520, 330));
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.setOpaque(false);

        codigolbl.setForeground(new java.awt.Color(255, 255, 255));
        codigolbl.setText("Cam001");

        cantparqlbl.setBackground(new java.awt.Color(204, 204, 204));
        cantparqlbl.setForeground(new java.awt.Color(255, 255, 255));
        cantparqlbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cantparqlbl.setText("0");
        cantparqlbl.setOpaque(true);

        parqbtn.setText("Parqueaderos");
        parqbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parqbtnActionPerformed(evt);
            }
        });

        puertabtn.setText("Puertas");
        puertabtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puertabtnActionPerformed(evt);
            }
        });

        notalbl.setForeground(new java.awt.Color(255, 0, 0));
        notalbl.setText("Para crear un Campus debe tener al menos 1 Parqueadero");

        nombreCampusTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreCampusTXTActionPerformed(evt);
            }
        });
        nombreCampusTXT.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                nombreCampusTXTPropertyChange(evt);
            }
        });
        nombreCampusTXT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nombreCampusTXTKeyReleased(evt);
            }
        });

        jButton2.setText("Aceptar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        cantpuertaslbl.setBackground(new java.awt.Color(204, 204, 204));
        cantpuertaslbl.setForeground(new java.awt.Color(255, 255, 255));
        cantpuertaslbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cantpuertaslbl.setText("0");
        cantpuertaslbl.setOpaque(true);

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Codigo:");
        jLabel3.setOpaque(true);

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Nombre:");
        jLabel2.setOpaque(true);

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Datos Campus");
        jLabel1.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(codigolbl, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(289, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(13, 13, 13)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(notalbl)
                            .addGap(4, 4, 4)
                            .addComponent(jButton2)
                            .addGap(6, 6, 6)
                            .addComponent(jButton1))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(133, 133, 133)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(parqbtn)
                                    .addGap(34, 34, 34)
                                    .addComponent(cantparqlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(puertabtn, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(34, 34, 34)
                                    .addComponent(cantpuertaslbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(nombreCampusTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(80, 80, 80)))
                    .addGap(14, 14, 14))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(180, 180, 180)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(codigolbl)
                .addContainerGap(199, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(8, 8, 8)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel3)
                    .addGap(6, 6, 6)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(3, 3, 3)
                            .addComponent(jLabel2))
                        .addComponent(nombreCampusTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(29, 29, 29)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(puertabtn)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(4, 4, 4)
                            .addComponent(cantpuertaslbl)))
                    .addGap(11, 11, 11)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(parqbtn)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(4, 4, 4)
                            .addComponent(cantparqlbl)))
                    .addGap(14, 14, 14)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(4, 4, 4)
                            .addComponent(notalbl))
                        .addComponent(jButton2)
                        .addComponent(jButton1))
                    .addContainerGap(30, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 20, 470, 250);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/fondo3.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(-4, -5, 510, 300);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        cs.setModificar(false);
        this.setVisible(false);
        ListaCampusGUI lcg = new ListaCampusGUI();
        lcg.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void puertabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puertabtnActionPerformed
        try {
            // TODO add your handling code here:
            String codigo = this.codigolbl.getText();
            String nombre = this.nombreCampusTXT.getText();
            if (!cs.isModificar()) {

                int cantpuertas = PuertasSERVICIO.getInstancia().getListapuertas().size();
                cs.crearCampus(codigo, nombre, cantpuertas);
            } else {
                cs.modificarCampus(codigo, nombre);
            }
            ListaPuertasGUI listaPuertasGUI = new ListaPuertasGUI();
            this.setVisible(false);
            listaPuertasGUI.setVisible(true);
        } catch (NombreCampusInvalidoException ex) {
            JOptionPane.showMessageDialog(this, "Ingrese un nombre de Campus");
        } catch (CampusConNombreExistenteException ex) {
            JOptionPane.showMessageDialog(this, "Ya existe un campus con nombre: " + this.nombreCampusTXT.getText());
        }


    }//GEN-LAST:event_puertabtnActionPerformed

    private void parqbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parqbtnActionPerformed
        // TODO add your handling code here:
        if (this.nombreCampusTXT.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Ingrese un nombre de Campus");
        } else {
            ListaParqueaderosGUI gUI = new ListaParqueaderosGUI();
            this.setVisible(false);
            gUI.setVisible(true);
        }
    }//GEN-LAST:event_parqbtnActionPerformed

    private void nombreCampusTXTKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreCampusTXTKeyReleased
        // TODO add your handling code here:
        this.puertabtn.setEnabled(this.nombreCampusTXT.getText().length() != 0 || this.nombreCampusTXT.getText() == null);
    }//GEN-LAST:event_nombreCampusTXTKeyReleased

    private void nombreCampusTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreCampusTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreCampusTXTActionPerformed

    private void nombreCampusTXTPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_nombreCampusTXTPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreCampusTXTPropertyChange

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            if (!cs.isModificar()) {
                // TODO add your handling code here:
                cs.GuardarCampus(this.nombreCampusTXT.getText());
                this.setVisible(false);
                ListaCampusGUI lcg = new ListaCampusGUI();
                lcg.setVisible(true);
                JOptionPane.showMessageDialog(this, "Campus Agregado Correctamente");
            } else {
                cs.GuardarCampusModificado(this.nombreCampusTXT.getText());
                cs.setModificar(false);
                this.setVisible(false);
                ListaCampusGUI lcg = new ListaCampusGUI();
                lcg.setVisible(true);
                JOptionPane.showMessageDialog(this, "Campus Modificado Correctamente");
                PuertasDAO.getInstancia().mostrar();
            }
        } catch (CampusRepetidoException ex) {
            JOptionPane.showMessageDialog(this, "El campus ya existe");
        } catch (CampusConNombreExistenteException ex) {
            JOptionPane.showMessageDialog(this, "Ya existe un campus con nombre: " + this.nombreCampusTXT.getText());
        } catch (Campusvacioexception ex) {
            JOptionPane.showMessageDialog(this, "No puede Crear un Campus sin parqueaderos");
        } catch (NombreCampusInvalidoException ex) {
            JOptionPane.showMessageDialog(this, "Ingrese un nombre de Campus");
        } catch (CampusSinPuertasException ex) {
            JOptionPane.showMessageDialog(this, "No Puede Crear un Campus Sin Puertas");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DatosCampusGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DatosCampusGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DatosCampusGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DatosCampusGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DatosCampusGUI().setVisible(true);
            }
        });
    }

    public void agregarnombreExistente() {

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cantparqlbl;
    private javax.swing.JLabel cantpuertaslbl;
    private javax.swing.JLabel codigolbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField nombreCampusTXT;
    private javax.swing.JLabel notalbl;
    private javax.swing.JButton parqbtn;
    private javax.swing.JButton puertabtn;
    // End of variables declaration//GEN-END:variables

}
